<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Zahnrad-Konfigurator für CAD</title>
    <style>
        body {
            font-family: 'Arial', sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
            color: #333;
            max-width: 1200px;
            margin: 0 auto;
        }
        h1 {
            color: #2c3e50;
            text-align: center;
            margin-bottom: 30px;
        }
        .container {
            display: flex;
            flex-wrap: wrap;
            gap: 20px;
        }
        .controls {
            flex: 1;
            min-width: 300px;
            background: #f9f9f9;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        }
        .preview {
            flex: 2;
            min-width: 400px;
            display: flex;
            flex-direction: column;
            align-items: center;
        }
        .gear-canvas {
            border: 1px solid #ddd;
            margin-bottom: 20px;
            max-width: 100%;
        }
        label {
            display: block;
            margin: 15px 0 5px;
            font-weight: bold;
        }
        input, select {
            width: 100%;
            padding: 8px;
            border: 1px solid #ddd;
            border-radius: 4px;
            box-sizing: border-box;
        }
        button {
            background-color: #3498db;
            color: white;
            border: none;
            padding: 10px 15px;
            margin-top: 15px;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
            width: 100%;
        }
        button:hover {
            background-color: #2980b9;
        }
        .download-options {
            display: flex;
            gap: 10px;
            margin-top: 10px;
        }
        .download-options button {
            flex: 1;
        }
        .svg-btn {
            background-color: #27ae60;
        }
        .svg-btn:hover {
            background-color: #219653;
        }
        .dxf-btn {
            background-color: #e67e22;
        }
        .dxf-btn:hover {
            background-color: #d35400;
        }
        .error {
            color: #e74c3c;
            margin-top: 5px;
            font-size: 14px;
        }
        @media (max-width: 768px) {
            .container {
                flex-direction: column;
            }
        }
    </style>
</head>
<body>
    <h1>Zahnrad-Konfigurator für CAD-Konstrukteure</h1>
    
    <div class="container">
        <div class="controls">
            <h2>Parameter</h2>
            
            <label for="module">Modul (mm):</label>
            <input type="number" id="module" min="0.1" step="0.1" value="1" oninput="updateGear()">
            
            <label for="teeth">Zähnezahl:</label>
            <input type="number" id="teeth" min="5" step="1" value="20" oninput="updateGear()">
            
            <label for="pressureAngle">Eingriffswinkel (Grad):</label>
            <input type="number" id="pressureAngle" min="14.5" max="30" step="0.5" value="20" oninput="updateGear()">
            
            <label for="thickness">Dicke (mm):</label>
            <input type="number" id="thickness" min="1" step="1" value="5" oninput="updateGear()">
            
            <label for="hubDiameter">Nabendurchmesser (mm):</label>
            <input type="number" id="hubDiameter" min="0" step="1" value="10" oninput="updateGear()">
            
            <label for="boreDiameter">Bohrungsdurchmesser (mm):</label>
            <input type="number" id="boreDiameter" min="0" step="0.1" value="5" oninput="updateGear()">
            
            <label for="keyway">Keilnut:</label>
            <select id="keyway" onchange="updateGear()">
                <option value="none">Keine</option>
                <option value="din6885">DIN 6885</option>
            </select>
            
            <div id="keywaySizeContainer" style="display: none;">
                <label for="keywaySize">Keilnut Größe:</label>
                <select id="keywaySize" onchange="updateGear()">
                    <option value="3x1.8">3×1,8 mm</option>
                    <option value="4x2.6">4×2,6 mm</option>
                    <option value="5x3.0">5×3,0 mm</option>
                    <option value="6x3.5">6×3,5 mm</option>
                    <option value="8x4.0">8×4,0 mm</option>
                    <option value="10x5.0">10×5,0 mm</option>
                    <option value="12x5.0">12×5,0 mm</option>
                </select>
            </div>
            
            <button onclick="generateGear()">Zahnrad generieren</button>
            
            <div class="download-options">
                <button class="svg-btn" onclick="downloadSVG()">Als SVG herunterladen</button>
                <button class="dxf-btn" onclick="downloadDXF()">Als DXF herunterladen</button>
            </div>
            
            <div id="error" class="error"></div>
        </div>
        
        <div class="preview">
            <h2>Vorschau</h2>
            <canvas id="gearCanvas" class="gear-canvas" width="500" height="500"></canvas>
            <div>
                <strong>Technische Daten:</strong>
                <div id="gearSpecs">Wird berechnet...</div>
            </div>
        </div>
    </div>

    <script>
        // Globale Variablen
        let gearData = null;
        const canvas = document.getElementById('gearCanvas');
        const ctx = canvas.getContext('2d');
        
        // Initialisierung
        document.addEventListener('DOMContentLoaded', function() {
            updateGear();
            document.getElementById('keyway').addEventListener('change', function() {
                document.getElementById('keywaySizeContainer').style.display = 
                    this.value === 'none' ? 'none' : 'block';
            });
        });
        
        // Zahnradparameter aktualisieren
        function updateGear() {
            const module = parseFloat(document.getElementById('module').value);
            const teeth = parseInt(document.getElementById('teeth').value);
            const pressureAngle = parseFloat(document.getElementById('pressureAngle').value);
            
            if (module <= 0 || teeth < 5) {
                document.getElementById('error').textContent = 
                    'Ungültige Eingabe: Modul muss > 0 und Zähnezahl ≥ 5 sein.';
                return;
            }
            
            document.getElementById('error').textContent = '';
            
            // Technische Daten berechnen
            const pitchDiameter = module * teeth;
            const addendum = module;
            const dedendum = 1.25 * module;
            const outerDiameter = pitchDiameter + 2 * addendum;
            const rootDiameter = pitchDiameter - 2 * dedendum;
            
            // Technische Daten anzeigen
            document.getElementById('gearSpecs').innerHTML = `
                <p>Teilkreisdurchmesser: ${pitchDiameter.toFixed(2)} mm</p>
                <p>Kopfkreisdurchmesser: ${outerDiameter.toFixed(2)} mm</p>
                <p>Fußkreisdurchmesser: ${rootDiameter.toFixed(2)} mm</p>
                <p>Zahnkopfhöhe: ${addendum.toFixed(2)} mm</p>
                <p>Zahnfußhöhe: ${dedendum.toFixed(2)} mm</p>
            `;
            
            // Skalierung für die Vorschau anpassen
            const scale = Math.min(400 / outerDiameter, 1) * 0.8;
            gearData = {
                module,
                teeth,
                pressureAngle,
                pitchDiameter,
                addendum,
                dedendum,
                outerDiameter,
                rootDiameter,
                thickness: parseFloat(document.getElementById('thickness').value),
                hubDiameter: parseFloat(document.getElementById('hubDiameter').value),
                boreDiameter: parseFloat(document.getElementById('boreDiameter').value),
                keyway: document.getElementById('keyway').value,
                keywaySize: document.getElementById('keywaySize').value,
                scale
            };
            
            drawGearPreview();
        }
        
        // Zahnrad in der Vorschau zeichnen
        function drawGearPreview() {
            if (!gearData) return;
            
            // Canvas leeren
            ctx.clearRect(0, 0, canvas.width, canvas.height);
            
            // Koordinatenursprung in die Mitte setzen
            ctx.save();
            ctx.translate(canvas.width / 2, canvas.height / 2);
            
            // Skalierung anwenden
            const displayDiameter = gearData.outerDiameter * gearData.scale;
            ctx.scale(gearData.scale, gearData.scale);
            
            // Zahnrad zeichnen
            drawGear(ctx, gearData);
            
            ctx.restore();
        }
        
        // Zahnrad zeichnen
        function drawGear(ctx, data) {
            // Nabendurchmesser und Bohrung zeichnen
            if (data.hubDiameter > 0) {
                ctx.beginPath();
                ctx.arc(0, 0, data.hubDiameter / 2, 0, Math.PI * 2);
                ctx.fillStyle = '#ddd';
                ctx.fill();
                ctx.strokeStyle = '#999';
                ctx.lineWidth = 1 / data.scale;
                ctx.stroke();
            }
            
            if (data.boreDiameter > 0) {
                ctx.beginPath();
                ctx.arc(0, 0, data.boreDiameter / 2, 0, Math.PI * 2);
                ctx.fillStyle = 'white';
                ctx.fill();
                ctx.strokeStyle = '#666';
                ctx.lineWidth = 1 / data.scale;
                ctx.stroke();
            }
            
            // Keilnut zeichnen (vereinfacht)
            if (data.keyway === 'din6885' && data.boreDiameter > 0) {
                const [width, height] = data.keywaySize.split('x').map(Number);
                const radius = data.boreDiameter / 2;
                const keywayDepth = height - radius * (1 - Math.cos(Math.asin(width / (2 * radius))));
                
                ctx.beginPath();
                ctx.moveTo(width / 2, -radius);
                ctx.lineTo(width / 2, -radius + keywayDepth);
                ctx.lineTo(-width / 2, -radius + keywayDepth);
                ctx.lineTo(-width / 2, -radius);
                ctx.closePath();
                ctx.fillStyle = 'white';
                ctx.fill();
                ctx.strokeStyle = '#666';
                ctx.stroke();
            }
            
            // Zähne zeichnen
            ctx.beginPath();
            const angle

            // Zähne zeichnen
            ctx.beginPath();
            const angleStep = (2 * Math.PI) / data.teeth;
            const halfAngleStep = angleStep / 2;
            const pressureAngleRad = data.pressureAngle * Math.PI / 180;
            
            // Zahnform-Parameter
            const baseRadius = (data.pitchDiameter / 2) * Math.cos(pressureAngleRad);
            const addendumRadius = (data.pitchDiameter / 2) + data.addendum;
            const dedendumRadius = (data.pitchDiameter / 2) - data.dedendum;
            
            // Zahnflanken als Evolvente approximieren
            for (let i = 0; i <= data.teeth; i++) {
                const angle = i * angleStep;
                const cosAngle = Math.cos(angle);
                const sinAngle = Math.sin(angle);
                
                // Zahnfuß (beginnend bei der Mitte zwischen zwei Zähnen)
                if (i === 0) {
                    const startAngle = -halfAngleStep;
                    const x = dedendumRadius * Math.cos(startAngle);
                    const y = dedendumRadius * Math.sin(startAngle);
                    ctx.moveTo(x, y);
                }
                
                // Linke Flanke (Evolvente)
                for (let j = 0; j <= 5; j++) {
                    const t = j / 5 * Math.PI / 2;
                    const x = baseRadius * (Math.cos(t) + t * Math.sin(t));
                    const y = baseRadius * (Math.sin(t) - t * Math.cos(t));
                    const rotatedX = x * cosAngle - y * sinAngle;
                    const rotatedY = x * sinAngle + y * cosAngle;
                    
                    if (j === 0) {
                        ctx.lineTo(rotatedX, rotatedY);
                    } else {
                        ctx.lineTo(rotatedX, rotatedY);
                    }
                }
                
                // Zahnkopf (Kreisbogen)
                const headAngle1 = angle + halfAngleStep;
                const headAngle2 = angle + angleStep - halfAngleStep;
                ctx.arc(0, 0, addendumRadius, headAngle1, headAngle2);
                
                // Rechte Flanke (Evolvente, gespiegelt)
                for (let j = 5; j >= 0; j--) {
                    const t = j / 5 * Math.PI / 2;
                    const x = baseRadius * (Math.cos(t) + t * Math.sin(t));
                    const y = -baseRadius * (Math.sin(t) - t * Math.cos(t));
                    const rotatedX = x * cosAngle - y * sinAngle;
                    const rotatedY = x * sinAngle + y * cosAngle;
                    ctx.lineTo(rotatedX, rotatedY);
                }
            }
            
            // Zahnrad füllen und konturieren
            ctx.closePath();
            ctx.fillStyle = '#a5d8ff';
            ctx.fill();
            ctx.strokeStyle = '#2c3e50';
            ctx.lineWidth = 1 / data.scale;
            ctx.stroke();
        }
        
        // Zahnrad generieren (für Export)
        function generateGear() {
            updateGear();
            if (!gearData) return;
            
            // Hier würden Sie die Daten für den Export vorbereiten
            alert('Zahnrad wurde generiert! Bereit für den Export.');
        }
        
        // Als SVG herunterladen
        function downloadSVG() {
            if (!gearData) return;
            
            // Hier würden Sie den SVG-Code generieren
            alert('SVG-Export wird vorbereitet...');
            // In einer echten Implementierung würden Sie hier:
            // 1. SVG-Code mit den Zahnradparametern generieren
            // 2. Einen Download-Link erstellen
        }
        
        // Als DXF herunterladen
        function downloadDXF() {
            if (!gearData) return;
            
            // Hier würden Sie den DXF-Code generieren
            alert('DXF-Export wird vorbereitet...');
            // In einer echten Implementierung würden Sie:
            // 1. DXF-Code mit den Zahnradparametern generieren
            // 2. Einen Download-Link erstellen
        }
    </script>
</body>
</html>
